### PR TITLE
enables localgov_base_helper for new installs

### LINKED ISSUE #488: Enable localgov_base_helper module
If we accept the https://github.com/localgovdrupal/localgov_base/pull/569, we will need to enable the helper module for that theme as well.

### PR DESCRIPTION
**Pull request by markconroy**
Closes localgovdrupal/localgov_microsites#488

### CODE REVIEW

**Comment by ekes** [comment]
To enable the module on existing sites we're going to have to write an update hook... somewhere. So adding the dependency on the module isn't necessary here I think.

**Comment by markconroy** [comment]
@ekes ready for a review again, please.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov_microsites/pull/487 is a better place.

See https://github.com/localgovdrupal/localgov_base/pull/622#issuecomment-2374875960

**Comment by finnlewis** [comment]
We decided to park the localgov_base_helper module for now, see https://github.com/localgovdrupal/localgov_base/commit/ae91066633b005518cc81eb23d6951cde71e6223

**Pull request closed without merging**
