### PR TITLE
Prevent access to /events if events aren't enabled

### LINKED ISSUE #275: Disable access to /events when events are turned off for a site
At the moment access to /events depends on whether there are any event nodes.

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #275

### CODE REVIEW

**Comment by stephen-cox** [comment]
Tests are failing because of https://github.com/localgovdrupal/localgov_microsites_base/issues/158

**Comment by stephen-cox** [comment]
Having fixed an issue in the theme which was breaking the tests they;re now failing on the f***ing media_library_edit missing schema issue. Shouldn't effect the review of this.

**Comment by finnlewis** [comment]
testing now

**Review by finnlewis — APPROVED** [review]
Seems to work for me locally. When I disable the events content type, I page not found at /events. With events enabled I get an empty list. 

Thanks @stephen-cox ! 

(Also noting that we are ignoring the missing schema test fails for now on the silly media_library_edit config)

**Pull request merged**
