### PR TITLE
Ability to accept invites.

### PR DESCRIPTION
**Pull request by ekes**
Avoid needing to see the invites to accept them (there's no permission to do so); and one less step that's not required anyway.

### CODE REVIEW

**Comment by msayoung** [comment]
Hmm - still not working. 
Also having a conflict now that we've disabled Anons from creating accounts.

**Comment by ekes** [comment]
We do want this, but yes it's not going to do all we need. 
Replacing the view is the best option that we can package now.

We do need to have people create accounts though... unless we investigate also wiring into something that generates the account and sends a resend password link.

**Comment by ekes** [comment]
> We do need to have people create accounts though... unless we investigate also wiring into something that generates the account and sends a resend password link.

The configuration was that by default new account requests went to moderation; but those that had invites got accepted directly with a one-time login link. So I think it does want to go back to that, even if it means that you might end up with a moderation queue of spam attempts.

**Comment by ekes** [comment]
Pushed commit should make it possible to get to page of invites and click on accept.

The UX is rubbish still though. The invite isn't descriptive, and on accept it just returns to the my invites page.
We are however now overriding the view so we could do it further. Redirecting to the group accepted would be one. The fact that you can't see what you are accepting is another, but probably more complicated.

**Comment by msayoung** [comment]
@ekes seems to work fine. As you say not a great UX. 
There's a coding standard that needs sorting. 

Have another PR here to require admin approval for vistor registrations: https://github.com/localgovdrupal/localgov_microsites/pull/331

**Review by msayoung — APPROVED** [review]

**Comment by finnlewis** [comment]
> @ekes seems to work fine. As you say not a great UX. There's a coding standard that needs sorting.
> 
> Have another PR here to require admin approval for vistor registrations: [localgovdrupal/localgov_microsites#331](https://github.com/localgovdrupal/localgov_microsites/pull/331)

I merged that one @msayoung

**Comment by finnlewis** [comment]
I've changed the function name for that coding standards fail.

**Pull request merged**
