### PR TITLE
Add service to enable / disable permissions per module.

### PR DESCRIPTION
**Pull request by ekes**
To be used by domain settings form to "enable/disable" modules per domain.

### CODE REVIEW

**Comment by ekes** [comment]
@todo The form

**Comment by ekes** [comment]
@stephen-cox Shall we just remove the kernel test?

**Comment by stephen-cox** [comment]
> Shall we just remove the kernel test?

Hopefully fixed :crossed_fingers:

**Comment by ekes** [comment]
It's green!

**Comment by stephen-cox** [comment]
Looks to work fine apart from some weirdness on the content type setting form. Things can be enabled, but the form shows is greyed out without a check so saving the form disables it.

Example
image

**Comment by ekes** [comment]
Tests require https://github.com/localgovdrupal/localgov_paragraphs/pull/72 (plus probably more) to fix the schema errors. Rest of tests should pass.

**Comment by finnlewis** [comment]
@stephen-cox is happy to bring this in now,

**Pull request merged**
