### PR TITLE
initial commit for hiding breadcrumbs on homepage

### LINKED ISSUE #388: Option to hide breadcrumbs on homepage
Tandem issue with https://github.com/localgovdrupal/localgov_microsites_base/issues/207

### PR DESCRIPTION
**Pull request by markconroy**
Closes #388

### CODE REVIEW

**Comment by markconroy** [comment]
@ekes and/or @stephen-cox  we might need to add an update hook to add this to existing sites.

**Comment by finnlewis** [comment]
@keelanfh asks if we should default the checkbox to be checked to 'hide the breadcrumb on the homepage'. 

@Adnan-cds thinks yes, default to checked.

**Comment by finnlewis** [comment]
@ekes am I right in thinking we're taking a simpler approach to hiding breadcrumbs? 

@markconroy see https://github.com/localgovdrupal/localgov_microsites_base/pull/214

I think if we go with that pull request, this one might be redundant, no?

**Comment by ekes** [comment]
> I think if we go with that pull request, this one might be redundant, no?

I see a +1 on that one so yes if Mark's happy.

**Pull request closed without merging**
