### PR TITLE
Assign the theme override permission to group admin, and make it a gr…

### PR DESCRIPTION
**Pull request by msayoung**
…oup permission

### CODE REVIEW

**Comment by msayoung** [comment]
The changes fix the problem, but now the tests aren't passing.

**Review by finnlewis — APPROVED** [review]
Tested locally and works a treat! 

I can now have my gin theme back as my admin theme! Yay! 

And I can set the front end to Stable, which is interesting!

Thanks @msayoung !

**Comment by msayoung** [comment]
thanks @finnlewis - I dont suppose you know why the tests aren't passing?

**Comment by msayoung** [comment]
@ekes suggests that perhaps the admin theme isn't set in the test, and that's why its failing.

**Comment by ekes** [comment]
```
Exception: Warning: Undefined array key ""
Drupal\localgov_microsites_group\Plugin\DomainGroupSettings\ThemeSettings->buildConfigurationForm()() (Line: 114)
```
Where 114:
```
[':site_admin' => $themes[$site_admin]->info['name']]
```
So I'd guess the undefined array key with a value of `''` is `$site_admin`.
```
$site_admin = $site_config->get('admin');
```
Which either means that's the wrong value for the config key 'admin'; or because it's in a test the admin theme hasn't been set.
I'm going to guess it's maybe the latter. Guess the way to tell is locally var_dump() the value (or whatever preferred better debug method) and visit the page on the site, and running the test.
If it is the latter it'll need setting explicitly in the test.
If the former, just have to work out the correct key.

**Comment by finnlewis** [comment]
We now need to re-test this against the 2.x branch to confirm if it works and review failing tests.

**Comment by msayoung** [comment]
@finnlewis seems to work - have merged 2.x in .

**Comment by stephen-cox** [comment]
Works fine - although we may want to assign this permission to Micrsosite admins by default.

Just merged and pushed the latests 2.x changes to check tests.

**Comment by stephen-cox** [comment]
Test failure that needs fixing before this can be merged:

```
 1) Drupal\Tests\localgov_microsites_group\Functional\ModuleSettingsFormTest::testDomainGroupForm
Exception: Warning: Undefined array key ""
Drupal\localgov_microsites_group\Plugin\DomainGroupSettings\ThemeSettings->buildConfigurationForm()() (Line: 114)


/var/www/html/web/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpClientMiddleware.php:49
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:204
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:153
/var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php:48
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:248
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:224
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:269
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:226
/var/www/html/vendor/guzzlehttp/promises/src/Promise.php:62
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:182
/var/www/html/web/core/tests/Drupal/Tests/DrupalTestBrowser.php:137
/var/www/html/vendor/symfony/browser-kit/Client.php:404
/var/www/html/vendor/friends-of-behat/mink-browserkit-driver/src/BrowserKitDriver.php:145
/var/www/html/vendor/behat/mink/src/Session.php:148
/var/www/html/web/core/tests/Drupal/Tests/UiHelperTrait.php:334
/var/www/html/web/modules/contrib/localgov_microsites_group/tests/src/Functional/ModuleSettingsFormTest.php:76
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:728
```

**Comment by msayoung** [comment]
@stephen-cox this flummoxed me so I gave up. Ekes had an idea of what the problem is (noted above):

```
Exception: Warning: Undefined array key ""
Drupal\localgov_microsites_group\Plugin\DomainGroupSettings\ThemeSettings->buildConfigurationForm()() (Line: 114)
Where 114:
```

`[':site_admin' => $themes[$site_admin]->info['name']]`
So I'd guess the undefined array key with a value of '' is $site_admin.

`$site_admin = $site_config->get('admin');`
Which either means that's the wrong value for the config key 'admin'; or because it's in a test the admin theme hasn't been set.
I'm going to guess it's maybe the latter. Guess the way to tell is locally var_dump() the value (or whatever preferred better debug method) and visit the page on the site, and running the test.
If it is the latter it'll need setting explicitly in the test.
If the former, just have to work out the correct key.

**Comment by stephen-cox** [comment]
Tests should be fixed - just set it to use an empty string if there's no default theme.

**Comment by stephen-cox** [comment]
Failing tests are now the expected ones which should be fixed with #286

**Pull request merged**
