### PR TITLE
Feature/add paragraphs to events

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by msayoung** [comment]
@markconroy - updated the install file in localgov_microsites_events to add the paragraph and banner fields to the event display, but we still need to create and place them in the field_groups. 

Google tells me you know how to do this ;) https://mark.ie/blog/creating-a-drupal-field-group-programmatically

So leaving with you to finish off.

**Comment by markconroy** [comment]
This is ready for review now.

**Comment by finnlewis** [comment]
Hey @markconroy - got a coding standards issue in the .install, needs a newline at the end.

**Comment by markconroy** [comment]
@finnlewis That's sorted now.

**Review by stephen-cox — APPROVED** [review]
Looks good :+1:

**Pull request merged**
