### PR TITLE
Only set 'Generate automatic url alias box' for new nodes

### LINKED ISSUE #408: "Generate automatic url alias box" is always checked when opened for editing
Problem: 
Custom path is being overwritten when doing successive edits. The only way to preserve a custom path on a page is to keep un-checking "Generate automatic url alias box" every time an edit is done.

Steps to recreate the issue:
Open a page for editing
Un-check the "Generate automatic url alias box" and enter a custom path
Save the page
Re-open the page again for editing
Observe the "Generate automatic url alias box" is ticked again
Save the page
Re-open the page again for editing
Observe the custom path has now been overwritten with the default value

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #408

### CODE REVIEW

**Comment by stephen-cox** [comment]
@ekes @finnlewis This is ready for review. The test failures are the ones that fail for all PRs. See: https://github.com/localgovdrupal/localgov_microsites_group/issues/396

**Review by finnlewis — APPROVED** [review]
Works for me @stephen-cox . Should this also be merged into 3.x ?

**Comment by finnlewis** [comment]
Discussing in Merge Monday and want to create a PR in 3.x branch before merging this.

- [ ] Create a corresponding pull request against the 3.x branch.

**Comment by finnlewis** [comment]
Created #423

**Pull request merged**
