### PR TITLE
sets display config for news

### LINKED ISSUE #152: Manage page display for news in full view mode

### PR DESCRIPTION
**Pull request by markconroy**
Closes #152

### CODE REVIEW

**Comment by msayoung** [comment]
May want to  consider this together: https://github.com/localgovdrupal/localgov_microsites_group/pull/149

**Comment by markconroy** [comment]
@stephen-cox @msayoung I've removed the config for the form/view displays now, so this PR _only_ creates the banner field for the news content type.

Let's get this merged and we can follow-up with programmatically adding the displays in our `hook_install()`

**Comment by stephen-cox** [comment]
I'm getting the following error when testing this:

```
Configuration objects provided by <em class="placeholder">localgov_microsites_news</em> have unmet dependencies: <em class="placeholder">field.field.node.localgov_news_article.lgms_banner (field.storage.node.lgms_banner)</em>
```

Where is `field.storage.node.lgms_banner` defined?

**Comment by stephen-cox** [comment]
> Where is field.storage.node.lgms_banner defined?

Ah, just needed to pull latest changes to include https://github.com/localgovdrupal/localgov_microsites_group/pull/154

**Review by stephen-cox — APPROVED** [review]
Looks good :+1:

**Pull request merged**
