### PR TITLE
Move to stable group_context_domain and update for API changes.

### PR DESCRIPTION
**Pull request by ekes**

### CODE REVIEW

**Comment by ekes** [comment]
Bumps group_context_domain module up to 1.0.0 (from alpha) and should fix any changes in the API (which also jumped from alpha to stable with just one major change - that I accounted for anyway).

I'd suggest the manual test for this: make sure composer installs 1.0.0 with this, and basic check site.

**Comment by finnlewis** [comment]
Thanks @ekes! I will test.

**Comment by finnlewis** [comment]
Without this branch, I get a fatal error on install.

```

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
PHP Fatal error:  Trait "Drupal\group_context_domain\Context\GroupFromDomainContextTrait" not found in /var/www/html/web/modules/contrib/localgov_microsites_group/modules/localgov_microsites_events/src/EventSubscriber/EventsListingCheckEventSubscriber.php on line 17

Fatal error: Trait "Drupal\group_context_domain\Context\GroupFromDomainContextTrait" not found in /var/www/html/web/modules/contrib/localgov_microsites_group/modules/localgov_microsites_events/src/EventSubscriber/EventsListingCheckEventSubscriber.php on line 17
 [warning] Drush command terminated abnormally.
Failed to run drush si localgov_microsites -y: exit status 1
PHP Fatal error:  Trait "Drupal\group_context_domain\Context\GroupFromDomainContextTrait" not found in /var/www/html/web/modules/contrib/localgov_microsites_group/modules/localgov_microsites_events/src/EventSubscriber/EventsListingCheckEventSubscriber.php on line 17

Fatal error: Trait "Drupal\group_context_domain\Context\GroupFromDomainContextTrait" not found in /var/www/html/web/modules/contrib/localgov_microsites_group/modules/localgov_microsites_events/src/EventSubscriber/EventsListingCheckEventSubscriber.php on line 17
 [warning] Drush command terminated abnormally.
Failed to run drush uli: exit status 1
```

With this branch, the install works!

**Comment by finnlewis** [comment]
@ekes I've also tested a local install, created 2 sites as a controller user, assigned users, logged in as admin users and created content. All seems to work very well.

Also, the enable / disable content types seems to work better than recent tests.

**Review by finnlewis — APPROVED** [review]
Thanks @ekes - this all works very well for me locally!

**Review by markconroy — APPROVED** [review]
This fixed my issue with microsites not installing. Thanks.

**Comment by finnlewis** [comment]
Thanks @markconroy !

**Pull request merged**
