### PR TITLE
Update font field descriptions

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Review by markconroy — APPROVED** [review]
This is such a clever way of showing all those fonts in one place. Merge it, QUICK!

**Comment by msayoung** [comment]
Unfortunately it's not _all_ the fonts as we have a couple not hosted by google. But better than nothing.

**Comment by willguv** [comment]
Ooo, can I see a screenshot? (On my phone so can’t review)

**Comment by msayoung** [comment]
@willguv 
At the moment I'm just providing help text that links to https://fonts.google.com/share?selection.family=Alegreya%20Sans%7CArvo%7CBarlow%7CCabin%7CIBM%20Plex%20Sans%7CInter%7CLibre%20Baskerville%7CLora%7CMerriweather%7COpen%20Sans%7CPT%20Sans%7CPT%20Serif%7CPublic%20Sans%7CSource%20Sans%20Pro%7CSpace%20Mono%7CVollkorn%7CWork%20Sans

**Pull request merged**
