### PR TITLE
Issue localgovdrupal/localgov_microsites#118 Initial import of localgov_news into groups.

### PR DESCRIPTION
**Pull request by ekes**
Tests pass :crossed_fingers: 
Terms not yet in the groups, separate issue #136

### CODE REVIEW

**Comment by stephen-cox** [comment]
With the inclusion of news in the profile (https://github.com/localgovdrupal/localgov_microsites/pull/188) tests should be passing, but there's an issue with a missing dependency on the link_attributes module.

**Comment by ekes** [comment]
Hm... https://github.com/search?q=org%3Alocalgovdrupal+link_attributes&type=code and
https://github.com/localgovdrupal/localgov_news/blob/2.x/localgov_news.info.yml#L21=
but not https://github.com/localgovdrupal/localgov_news/blob/2.x/composer.json

**Comment by ekes** [comment]
We should get localgovdrupal/localgov_news#63 merged Monday.

I've also now noticed that:

Newsroom creates a /news node by default on installation.
It gets in there before our default content.
/node/1 becomes a newsroom node.
When you create a microsite it's coded to clone /node/1 by default.
BOOM!

Suggested solutions?
 - When setting the default content configuration lookup the content by title?
 - In any case add in some checks for content type before creating the GroupContent.
 - Something else?
 
@stephen-cox any ideas?

**Comment by ekes** [comment]
Dependencies in LocalGov News https://github.com/localgovdrupal/localgov_news/pull/63 will need a release.

**Review by finnlewis — APPROVED** [review]
Tested locally, installs fine and I can create news rooms and news on each microsite. Good to get this in and tidy up the styling next sprint I reckon.

**Pull request merged**
