### PR TITLE
202407 media search name

### PR DESCRIPTION
**Pull request by anthonylindsay**
added group node admin view override 
- adds a 'search by name' filter

### CODE REVIEW

**Comment by anthonylindsay** [comment]
issue: https://github.com/localgovdrupal/localgov_microsites/issues/450

**Review by Polynya — DISMISSED** [review]

**Comment by ekes** [comment]
@Polynya have you manually tested this? If so I'm happy.

**Comment by stephen-cox** [comment]
We'll test on a clean install before merging - otherwise looks fine.

**Comment by finnlewis** [comment]
I just tested on a clean install locally, works a treat.  Thanks @anthonylindsay !

I wonder if you merge back from the 4.x branch to your feature branch if the deprecated warnings will we resolved. 

Either way, not a blocker to merging as they are clearly unrelated to the changes introduced here.

**Review by finnlewis — APPROVED** [review]

**Pull request merged**
