### PR TITLE
Enable automatic generation of URLs

### LINKED ISSUE #271: Domain Path PathAuto
- [x] Create three pathauto aliases for same value, they _are_ created `string`, `string-1`, `string-2` _but_ `string-1` is also replaced as the link _to_ the content for `string-1`. At least that's my manual testing of https://www.drupal.org/project/domain_path/issues/3285213 Needs automated tests and a fix
 - [x] Pathauto checkbox is always _off_ by default, no way of changing this, you have to select it
 - [ ] We probably want to extend the automatic replacement to use group alias rather than `-1` in the first instance

_Originally posted by @ekes in https://github.com/localgovdrupal/localgov_microsites/issues/146#issuecomment-1168568432_

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #271

### CODE REVIEW

**Comment by stephen-cox** [comment]
With the changes here, Pathauto creates aliases on the controller site for all content. While this is not great, a bigger problem is all the content being available on the controller site anyway, so I suggest we discuss this on #276

**Comment by finnlewis** [comment]
Not tested yet, hope to do so later today.

**Comment by ekes** [comment]
[x] Creates auto aliases for domains;
[x] Remembers state of checkbox after save on initial test.
[ ] Checkbox isn't defaulted on for new posts. I'm assuming we don't need this to be configurable, we do it for microsites only in this module and just make it always on?

It seems to create the autopath for the default domain no matter the state of the checkbox in the first instance.
It uses the default domain path for the site domain as well if it's not generated a site specific one. No way to disable.

Token replacement, for 'parent post'/'entity reference' path, uses the path of the domain the item is posted on -- this is just a reason to encourage _not_ editing content on the master site, nor sharing content.

**Review by finnlewis — APPROVED** [review]
Yeah baby! It does seem to work on multiple microsites. 

I agree it is odd to be able to edit the content on the controller site as it needs it's domain / group context. 

Are we able to default the checkbox to be on when creating new content on the microsite?

**Comment by stephen-cox** [comment]
Tests are failing because of https://github.com/localgovdrupal/localgov_microsites_base/issues/158

**Comment by stephen-cox** [comment]
Tests are now failing on the f***ing media_library_edit missing schema issue. I'm just going to merge this

**Pull request merged**
