### PR TITLE
Added dummy menu_link_reference module and update hook to uninstall it

### LINKED ISSUE #390: Unable to create new microsites: The "field_item:menu_link_reference" plugin does not exist.
When trying to create a new microsite on the demo site we get an error: Drupal\Core\Entity\EntityStorageException: The "field_item:menu_link_reference" plugin does not exist.

Looks like the menu_link_reference submodule of group_content_menu has been removed with no upgrade path: https://www.drupal.org/project/group_content_menu/issues/3333968

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #390

### CODE REVIEW

**Comment by stephen-cox** [comment]
I have successfully used this to fix the Demo Microsite install at: https://demo.microsites.localgovdrupal.org/

**Comment by finnlewis** [comment]
wicked - testing!

**Review by finnlewis — APPROVED** [review]
Works for me @stephen-cox !

**Review by ekes — APPROVED** [review]
Makes sense.

**Comment by stephen-cox** [comment]
@ekes @finnlewis I have this working with pinned commits, although I've moved group_permissions to 2.0.0-alpha5, which has all the equivalent commits, and localgov_forms to beta1.

Is there an issue tracking localgov_forms releases from now on?

**Comment by finnlewis** [comment]
@stephen-cox makes perfect sense to track release tags of localgov_forms. I guess we just never updated the require since the release of the beta tag in December.

**Pull request merged**
