### PR TITLE
Feature/473 webform submission test

### PR DESCRIPTION
**Pull request by ekes**
NB it relies on #469 as it has the login out trait.

### CODE REVIEW

**Comment by finnlewis** [comment]
I'm looking at these conflicts,

**Review by finnlewis — APPROVED** [review]
I'm happy with this!

Tests are now all passing too :)

**Comment by finnlewis** [comment]
@stephen-cox fancy providing a second pair of eyes ?

**Review by stephen-cox — APPROVED** [review]
I've read through the tests and they make sense to me. The tests are also passing so happy for this to be merged.

**Comment by finnlewis** [comment]
Yay, thanks @stephen-cox , always good to have multiple reviews :)

**Pull request merged**
