### PR TITLE
Feature/1.x/admin theme microsite view

### LINKED ISSUE #22: Consistent use of the admin theme
All actions in the group want to be defined as administration and use the admin theme. Just viewing content that is outside.

### PR DESCRIPTION
**Pull request by ekes**
Fixes #22

### CODE REVIEW

**Comment by ekes** [comment]
Realize there's still c&p use statements in there. To tidy up.

**Comment by finnlewis** [comment]
This want merging yet @ekes ?

**Comment by ekes** [comment]
@finnlewis Now for the minimum set of requirements of #22 and #27

**Comment by finnlewis** [comment]
Thanks @ekes 

Looks to install fine and I do now have the 'Users' and 'Content' tabs up. 

I don't see a way to add a user to the microsite yet, maybe we create another issue for that unless I'm looking in the wrong place?

Similarly, I guess we'll need a 'Add content' link from the 'Content' tab that takes us to /node/add? Also a new isssue?

Otherwise I guess you'll want to merge this as is for now.

**Review by finnlewis — APPROVED** [review]

**Comment by ekes** [comment]
> @ekes
[Restore local actions to microsites node, members. Rename members users.](https://github.com/localgovdrupal/localgov_microsites_group/pull/24/commits/f57c04913f4521198bec55eb744b7b574cb99f64)
[f57c049](https://github.com/localgovdrupal/localgov_microsites_group/pull/24/commits/f57c04913f4521198bec55eb744b7b574cb99f64)

I'd forgotten to push it, well to the right place anyway.

**Pull request merged**
