### PR TITLE
Use group_term alpha5

### LINKED ISSUE #376: Tests failing: Undefined array key "gc__taxonomy_term"
Tests are failing with `Exception when installing config for module group, message was: Undefined array key "gc__taxonomy_term"`

Looks to be a result of merging #372

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #376

### CODE REVIEW

**Comment by stephen-cox** [comment]
Fixes the 'Undefined array key "gc__taxonomy_term"' failures, but tests are still failing. New failures should be fixed with #391

**Comment by finnlewis** [comment]
Nice work @stephen-cox 

We now just have this other error in the phpunit tests, which I think is related to this: 
https://www.drupal.org/project/group_content_menu/issues/3333968

**Comment by stephen-cox** [comment]
> We now just have this other error in the phpunit tests, which I think is related to this: https://www.drupal.org/project/group_content_menu/issues/3333968

Should be fixed with #391

**Review by finnlewis — APPROVED** [review]
Very cool!

**Pull request merged**
