### PR TITLE
Adds the layout paragraph to news content type

### PR DESCRIPTION
**Pull request by msayoung**
@stephen-cox - here's the config for adding the layout paragraph field to news, but as predicted we cant install the core.entity_*_display files as they already exist. 

Can you take it from here?

### CODE REVIEW

**Comment by stephen-cox** [comment]
@msayoung I have finally implemented the install hook to update field display settings when adding the paragraph field. Are the applied settings looking okay?

Apologies for the delay; I went down a rabbit hole trying to get a test working. It still doesn't work. I will add it when I crack it,

**Comment by msayoung** [comment]
Great except I get this error: 

```
The website encountered an unexpected error. Please try again later.
Error: Call to a member function getDataDefinition() on null in Drupal\facets\Entity\Facet->getDataDefinition() (line 645 of modules/contrib/facets/src/Entity/Facet.php).
Drupal\facets\Entity\Facet->getDataDefinition('localgov_directory_facets_filter') (Line: 114)
Drupal\entity_reference_facet_link\Plugin\Field\FieldFormatter\EntityReferenceFacetFormatterBase->settingsForm(Array, Object) (Line: 446)
Drupal\field_ui\Form\EntityDisplayFormBase->buildFieldRow(Object, Array, Object) (Line: 40)
Drupal\field_ui\Form\EntityViewDisplayEditForm->buildFieldRow(Object, Array, Object) (Line: 209)
Drupal\field_ui\Form\EntityDisplayFormBase->form(Array, Object) (Line: 106)
Drupal\Core\Entity\EntityForm->buildForm(Array, Object)
call_user_func_array(Array, Array) (Line: 531)
Drupal\Core\Form\FormBuilder->retrieveForm('entity_view_display_edit_form', Object) (Line: 278)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 97)
Drupal\autosave_form\Form\AutosaveFormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 158)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 709)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

when visiting: https://localgov-micro.lndo.site/admin/structure/types/manage/localgov_news_article/display

**Comment by msayoung** [comment]
Actually, I'm getting that error anyway, so probably not related. But I can't test it unfortunately.

**Comment by markconroy** [comment]
I made a tiny commit to set the field formatter for the paragraphs field to use layout paragraphs. I'm happy with this PR now @msayoung

**Comment by msayoung** [comment]
This is working great now. I think we can merge once the tests pass.

**Comment by markconroy** [comment]
Seems to be hanging for me now. Although when it was broken for you earlier, it was working for me.

**Comment by msayoung** [comment]
> Seems to be hanging for me now. Although when it was broken for you earlier, it was working for me.

At what point is it hanging @markconroy  - it was on the promo page PR that the site install was hanging earlier. Do you still have that branch checked out?

**Comment by markconroy** [comment]
Seems to be working fine now. I had to do a new composer update to clear a few things out.

**Review by markconroy — APPROVED** [review]

**Pull request merged**
