### PR TITLE
Feature/348 group media

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Review by msayoung — APPROVED** [review]

**Comment by msayoung** [comment]
When I try to add media from the Media overview i get the following. 

```
The website encountered an unexpected error. Please try again later.
ArgumentCountError: Too few arguments to function Drupal\groupmedia\Controller\GroupMediaController::addPageBundles(), 2 passed in /app/web/modules/contrib/groupmedia/src/Controller/GroupMediaController.php on line 44 and exactly 3 expected in Drupal\groupmedia\Controller\GroupMediaController->addPageBundles() (line 72 of modules/contrib/groupmedia/src/Controller/GroupMediaController.php).
Drupal\groupmedia\Controller\GroupMediaController->addPageBundles(Object, 1) (Line: 44)
Drupal\groupmedia\Controller\GroupMediaController->addPage(Object, 1, NULL)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 169)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 709)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by msayoung** [comment]
Also, if you try to add a remote video, you seem to be able to create it, but it doesn't appear in the group to be chosen. 

From a piece of content
- add section
- add video
- Add media
- Add Remote URL
- fill in the meta data , hit save
- Nothing in the library to select.

**Comment by finnlewis** [comment]
seems to me that as soon as we enable multiple media types in the group content plugin, the  /group/2/media/create page stops working

With just one media content plugin, it works.

With more than one, we get the error maria mentions above. 

> ArgumentCountError: Too few arguments to function Drupal\groupmedia\Controller\GroupMediaController::addPageBundles(), 2 passed in /app/web/modules/contrib/groupmedia/src/Controller/GroupMediaController.php on line 44 and exactly 3 expected in Drupal\groupmedia\Controller\GroupMediaController->addPageBundles() (line 72 of modules/contrib/groupmedia/src/Controller/GroupMediaController.php).

This is fair enough. This line: https://git.drupalcode.org/project/groupmedia/-/blob/4.0.x/src/Controller/GroupMediaController.php#L44 does need another argument for addPageBundles, see https://git.drupalcode.org/project/groupmedia/-/blob/4.0.x/src/Controller/GroupMediaController.php#L72

Adding that then gives: 

> 
> The website encountered an unexpected error. Please try again later.
> TypeError: Illegal offset type in isset or empty in Drupal\groupmedia\Controller\GroupMediaController->addPage() (line 45 of modules/contrib/groupmedia/src/Controller/GroupMediaController.php). 

Editing those lines to get the actual bunlde name
```
    foreach ($this->addPageBundles($group, $create_mode, $base_plugin_id) as $plugin_id => $bundle) {
      $bundle_name = $bundle->getOriginalId();
      if (!empty($build['#bundles'][$bundle_name])) {
```
> 
Drupal\Component\Plugin\Exception\PluginNotFoundException: Plugin ID 'microsite-group_media-document' was not found. in Drupal\Core\Plugin\DefaultLazyPluginCollection->initializePlugin() (line 79 of core/lib/Drupal/Core/Plugin/DefaultLazyPluginCollection.php). 

Hmmm....

I need to down tools now, but I think this is a bug in groupmedia that we need to fix.

**Comment by finnlewis** [comment]
@msayoung I made a patch on drupal.org that should fix the multiple media. Just testing it now.

**Comment by finnlewis** [comment]
@msayoung I've added another hook_form_FORM_ID_alter to get the videos submitting into the group.

**Review by msayoung — APPROVED** [review]

**Comment by finnlewis** [comment]
Yay! Thank you @stephen-cox !

**Pull request merged**
