### PR TITLE
Fix module toggle by site

### PR DESCRIPTION
**Pull request by stephen-cox**

### CODE REVIEW

**Comment by finnlewis** [comment]
Testing now

**Comment by stephen-cox** [comment]
> Testing now

The failing test means I'm not sure the logic changes are correct, so I'm marking this is draft as it's not ready for review yet.

**Review by finnlewis — APPROVED** [review]
Functionality seems good locally... I can now toggle on and off individual content types without affecting the others.

**Comment by finnlewis** [comment]
@ekes maybe could you check if this works with Group 3.x?

**Comment by ekes** [comment]
Note #252 related, and #296 
If all is well #305 is fixed, so now can check these.

**Comment by ekes** [comment]
Tests certainly need fixing, but from a front end perspective it certainly seems to be doing the trick.

**Comment by finnlewis** [comment]
In Merge Monday, @stephen-cox recalls that the tests were not testing the right thing, so we either remove the bad tests or fix the tests.

**Comment by ekes** [comment]
> [Tests fixes: 3 out of 4. 1 to go.](https://github.com/localgovdrupal/localgov_microsites_group/pull/286/commits/42377a3de7f90d6ad2f85d2c6d3dc7580d5edc78)

And the 1 is breaking because it's broken, not because the test is wrong.

**Comment by ekes** [comment]
Tests pass now. Suggest maybe a follow-up to see if when GroupPermission entity is saved it shouldn't automatically flush some cache (we have two drupal_flush_all_caches() in the test that might be rendered unnecessary).

**Comment by finnlewis** [comment]
Coding standards now pass.

But @ekes I can't enable / disable blogs or events. 

news and directories seem to work OK.

Site 1 settings from control site: 

image

node add create page on site 1 as a microsite editor 

image

**Comment by stephen-cox** [comment]
This largely looks to work fine. There is some strange caching going on. The add new content screen doesn't always get updated. After a full cache rebuild things seem to work as expected.

**Comment by ekes** [comment]
Doesn't seem to be as reliable as clearing cache. There seems to be something not quite right about the way we're creating the group permissions entity. I'm prodding.

**Comment by finnlewis** [comment]
This does now work for me, if I clear the cache.

**Pull request merged**
