### PR TITLE
Add block config for main and utility menus

### PR DESCRIPTION
**Pull request by stephen-cox**
Regions are added to the theme with this PR: https://github.com/localgovdrupal/localgov_microsites_base/pull/10

Closes  #39

### CODE REVIEW

**Comment by stephen-cox** [comment]
Group menus aren't rendering. This looks to be an issue with the theme working with Groups. Looking into it now

**Comment by ekes** [comment]
This makes an (optional) but circular dependency on localgov_microsites_base theme?

The theme has to depend on this module, the module doesn't have to depend on the theme. So you only get this optional configuration if the theme is there, this module will always be there if the theme is there. So it would make sense for this to be in the theme?

**Comment by finnlewis** [comment]
> Group menus aren't rendering. This looks to be an issue with the theme working with Groups. Looking into it now

Yeah, I'm not seeing menus after adding links to them on the microsite: https://localgov-micro-1.lndo.site/ 

But the blocks do get placed on a fresh install, so that's nice :)

**Comment by stephen-cox** [comment]
I was a bit hasty creating this PR. There's a fundamental issue placing the Group Content Menu blocks.

To determine the group it use the GroupRouteContext which comes with Group the module. This determines the group from the current route and doesn't work with domains.

The easiest fix looks to be to create a custom Block plugin that inherits from the Group Content Menu block and sets the group rather than using the context. It would be nice if we could just override the context but this doesn't seem possible.

Inheriting the block and modifying behaviour seems a little flaky, but works for now. Other thoughts on solutions to this are welcome.

**Comment by ekes** [comment]
Options: 
- adding more contexts; we certainly need them domains; for example there isn't one for the default domain :-/ (at least not without knowing what the hostname is already - which isn't good for a generic view) #38
- only show content in the group context, so for example content would have to be displayed on the group content relationship #23

**Comment by stephen-cox** [comment]
Thanks @ekes, I have updated the code here to make it clear it needs replacing or rewriting once we have agreement on how to determine content context. I've also moved the block placement config to the theme with https://github.com/localgovdrupal/localgov_microsites_base/pull/11

**Review by ekes — APPROVED** [review]
Happy with this as a temporary fix.

Think answering the questions on #23 might be the best solution when we start again after testing.

**Comment by finnlewis** [comment]
You happy to merge this @stephen-cox or do you want me to test it too?

**Comment by stephen-cox** [comment]
@finnlewis Merged it - you can test it with this PR https://github.com/localgovdrupal/localgov_microsites_base/pull/11

**Pull request merged**
