### PR TITLE
Adds reset button and author column for group node view

### PR DESCRIPTION
**Pull request by anthonylindsay**
config change for new installs for admin view of nodes for a microsite.

### CODE REVIEW

**Comment by markconroy** [comment]
@anthonylindsay is the author column an addition to this: https://github.com/localgovdrupal/localgov_microsites_group/pull/446 where we allow filtering by title and author for new installs?

If so, perhaps you can amend your PR to only include the reset button if the other part is already covered.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by anthonylindsay** [comment]
No, it's not adding a filter. It's adding the display column and the reset button.
Should be safe alongside whatever the other issue does methinks.

You get this:

nodes

**Comment by stephen-cox** [comment]
We'll test on a clean install before merging - otherwise looks fine.

**Comment by finnlewis** [comment]
Thanks @anthonylindsay ! Just testing locally.

As an aside, I've invited you to the Github organisation https://github.com/localgovdrupal, so once you accept, you should be able to make feature branches here in the repository. One advantage to this is that other people can add commits and collaborate on a pull request. We have some Git branch naming conventions noted here https://github.com/localgovdrupal/localgov/wiki/Git-branch-naming-conventions

**Comment by finnlewis** [comment]
Confirmed this works fine on a fresh install: 

image

**Review by finnlewis — APPROVED** [review]

**Comment by anthonylindsay** [comment]
Cheers, Finn!

**Pull request merged**
