### PR TITLE
Update workflow on 1.x branch

### LINKED ISSUE #114: Coding standards problems
```
FILE: ...ntrib/localgov_microsites_group/localgov_microsites_group.module
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 6 LINES
----------------------------------------------------------------------
   1 | ERROR | [x] Missing file doc comment
  21 | ERROR | [x] Missing function doc comment
 158 | ERROR | [ ] The array declaration extends to column 142 (the
     |       |     limit is 80). The array content should be split up
     |       |     over multiple lines
 167 | ERROR | [x] Case breaking statements must be followed by a
     |       |     single blank line
 169 | ERROR | [x] Case breaking statements must be followed by a
     |       |     single blank line
 188 | ERROR | [x] Doc comment short description must be on the first
     |       |     line
----------------------------------------------------------------------
PHPCBF CAN FIX THE 5 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...localgov_microsites_group/src/Entity/MicrositeGroupInterface.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 5 | ERROR | [x] Missing interface doc comment
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: .../contrib/localgov_microsites_group/src/Entity/MicrositeGroup.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 7 | ERROR | [x] Missing class doc comment
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...gov_microsites_group/src/Controller/DomainGroupAddController.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
 11 | WARNING | [x] Unused use statement
 12 | WARNING | [x] Unused use statement
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...rib/localgov_microsites_group/src/Form/DomainGroupContentAdd.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 8 | ERROR | [x] Missing class doc comment
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...es/contrib/localgov_microsites_group/src/Form/DomainGroupAdd.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
  8 | ERROR | [x] Missing class doc comment
 22 | ERROR | [x] Whitespace found at end of line
 23 | ERROR | [x] Inline control structures are not allowed
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...trib/localgov_microsites_group/src/Form/DomainGroupConfigAdd.php
----------------------------------------------------------------------
FOUND 2 ERRORS AND 2 WARNINGS AFFECTING 4 LINES
----------------------------------------------------------------------
   9 | WARNING | [x] Unused use statement
  68 | ERROR   | [x] Expected 1 blank line after function; 2 found
 103 | WARNING | [ ] Unused variable $store.
 217 | ERROR   | [x] Expected 1 space after "="; 2 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...contrib/localgov_microsites_group/src/GroupExtraFieldDisplay.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 10 | ERROR | [x] Missing class doc comment
 31 | ERROR | [x] Whitespace found at end of line
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...es/contrib/localgov_microsites_group/src/GroupDefaultContent.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 4 LINES
----------------------------------------------------------------------
  7 | WARNING | [x] Unused use statement
 15 | WARNING | [ ] The class short comment should describe what the
    |         |     class does and not simply repeat the class name
 65 | WARNING | [ ] Node::load calls should be avoided in classes,
    |         |     use dependency injection instead
 86 | WARNING | [x] A comma should follow the last multiline array
    |         |     item. Found: ]
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...v_microsites_group/src/EventSubscriber/ReplicateGroupContent.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 19 | ERROR | [x] Do not append variable name "$replicator" to the
    |       |     type declaration in a member variable comment
 37 | ERROR | [x] Whitespace found at end of line
 39 | ERROR | [x] Data types in @param tags need to be fully
    |       |     namespaced
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
FILE: ...ov_microsites_group/src/Plugin/Block/MicrositeGroupMenuBlock.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 42 | ERROR | Parameter $class_resolver is not described in comment
----------------------------------------------------------------------
FILE: ...rib/localgov_microsites_group/tests/src/Functional/LoginTest.php
----------------------------------------------------------------------
FOUND 8 ERRORS AFFECTING 8 LINES
----------------------------------------------------------------------
 12 | ERROR | [x] Whitespace found at end of line
 30 | ERROR | [ ] Do not disable strict config schema checking in
    |       |     tests. Instead ensure your module properly declares
    |       |     its schema for configurations.
 38 | ERROR | [x] Perl-style comments are not allowed; use "//
    |       |     Comment" instead
 39 | ERROR | [x] Perl-style comments are not allowed; use "//
    |       |     Comment" instead
 41 | ERROR | [x] Perl-style comments are not allowed; use "//
    |       |     Comment" instead
 45 | ERROR | [x] Perl-style comments are not allowed; use "//
    |       |     Comment" instead
 66 | ERROR | [x] Whitespace found at end of line
 98 | ERROR | [x] Whitespace found at end of line
----------------------------------------------------------------------
PHPCBF CAN FIX THE 7 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #114

### CODE REVIEW

**Comment by stephen-cox** [comment]
Issue for coding standards problems #114 

Issue for failing test #115

**Comment by stephen-cox** [comment]
@finnlewis @ekes This fixes coding standard issues with the Microsites Group module as well as adding Github testing.

Tests now run with https://github.com/localgovdrupal/drupal-container/commit/6594dbf577019a48faba0f7d13600d040eb9a3ff

Te coding standards issue should be fixed with #117. The deprecation failures should be fixed with #118

**Comment by stephen-cox** [comment]
@finnlewis @ekes Tests all passing on this now. Would be good to get this merged so we have our tests running on PRs

**Review by finnlewis — APPROVED** [review]
Looks good to me and tests pass

**Pull request merged**
