### PR TITLE
adds fields needed for sprint 3

### LINKED ISSUE #32: Add sprint 3 fields
Adds fields for:
- Secondary colour
- Text colour dark
- Text colour light
- Spacing
- Heading font weight
- All fields for headings 1 - 6

Updates:
- Footer logos to use media
- Field group labels for Heading overrides
- Field group labels for Global styles

Removes:
- Main menu field
- Utility menu field
- Housekeeping menu field

### PR DESCRIPTION
**Pull request by markconroy**
Closes #32

### CODE REVIEW

**Comment by finnlewis** [comment]
Getting some odd behaviour.

Fresh install, create a microsite, then the view microsite entity gives: 

```
The website encountered an unexpected error. Please try again later.

InvalidArgumentException: Field lgms_base_line_height is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of core/lib/Drupal/Core/Entity/ContentEntityBase.php).
Drupal\Core\Entity\ContentEntityBase->get('lgms_base_line_height') (Line: 48)
localgov_microsites_base_preprocess_html(Array, 'html', Array) (Line: 287)
Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 162)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 163)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 163)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

And the edit microsite does not appear to have the expected fieldsets and fields.

**Comment by finnlewis** [comment]
@msayoung is up for tackling this on Monday

**Comment by finnlewis** [comment]
On the default branch, at https://localgov-micro.lndo.site/admin/group/types/manage/microsite/form-display we have the config for all the form field groups like: 

image

On this branch, we don't, so I think something got missed or lost.

**Comment by msayoung** [comment]
There was some missing field config which was causing the error, and making the field grouping fail. 
I've added this back in.

@finnlewis wanna check?

**Review by finnlewis — APPROVED** [review]
Thanks for fixing this @msayoung - shall we go ahead and merge?

**Pull request merged**
