### PR TITLE
Only set 'Generate automatic url alias box' for new nodes #408

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by finnlewis** [comment]
@stephen-cox this PR is not installing.

It looks like we're trying to alias against LATEST_RELEASE where we actually want a 3.x-dev alias, no? 

```
composer --working-dir=html config repositories.1 vcs git@github.com:${LOCALGOV_DRUPAL_PROJECT}.git
  composer global config github-oauth.github.com ***
  composer --working-dir=./html require --with-all-dependencies ${LOCALGOV_DRUPAL_PROJECT}:"${COMPOSER_REF} as ${LATEST_RELEASE}"
  shell: /usr/bin/bash -e {0}
  env:
    LOCALGOV_DRUPAL_PROJECT: localgovdrupal/localgov_microsites_group
    LOCALGOV_DRUPAL_PROJECT_PATH: web/modules/contrib/localgov_microsites_group
    GIT_BASE: [3](https://github.com/localgovdrupal/localgov_microsites_group/actions/runs/6362377018/job/17277444344?pr=426#step:11:3).x
    GIT_BRANCH: fix/3.x/[4](https://github.com/localgovdrupal/localgov_microsites_group/actions/runs/6362377018/job/17277444344?pr=426#step:11:4)0[8](https://github.com/localgovdrupal/localgov_microsites_group/actions/runs/6362377018/job/17277444344?pr=426#step:11:8)-generate-alias-always-on
    HEAD_USER: localgovdrupal
    COMPOSER_REF: dev-fix/3.x/408-generate-alias-always-on
    LATEST_RELEASE: 2.x-dev
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
Changed current directory to /home/runner/.composer
./composer.json has been updated
Running composer update localgovdrupal/localgov_microsites_group --with-all-dependencies
Removing package drupal/domain_path so that it can be re-installed and re-patched.
  - Removing drupal/domain_path (1.3.0)
Deleting web/modules/contrib/domain_path - deleted
Loading composer repositories with package information
                                                      Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - localgovdrupal/localgov_microsites is locked to version 3.x-dev and an update of this package was not requested.
    - localgovdrupal/localgov_microsites 3.x-dev requires localgovdrupal/localgov_microsites_group 3.x-dev -> found localgovdrupal/localgov_microsites_group[3.x-dev] but it conflicts with your root composer.json require (dev-fix/3.x/408-generate-alias-always-on as 2.x-dev).

**Comment by finnlewis** [comment]
@stephen-cox could you help me work out what's wrong with the test configuration here?

**Comment by stephen-cox** [comment]
This is borked due to the Microsites Base theme requiring localgov_microsites_group:3.x-dev while the profile requires localgov_microsites_group:^3.0.0@alpha

Should be fixed with https://github.com/localgovdrupal/localgov_microsites_base/pull/231

**Comment by stephen-cox** [comment]
Tests are running again now there's a https://github.com/localgovdrupal/localgov_microsites_base/releases/tag/2.0.0-beta9 release of the theme.

**Review by stephen-cox — APPROVED** [review]
Just a port to 3.x of changes already in 2.x

**Comment by stephen-cox** [comment]
@finnlewis Waiting for you to merge and release :smile:

**Pull request merged**
