### PR TITLE
Enable directory venues as part of a site install 

### LINKED ISSUE #108: Add venues to microsites directories
From: https://github.com/localgovdrupal/localgov_microsites_group/pull/106

Directory venues aren't enabled by default because the Drupal site install hangs indefinitely when trying to enable something to do with this. It is possible to enable venues after a site install, so I suspect some sort of run condition, but haven't spent much time investigating this yet.

## User story

As a microsite admin
I want to add a directory entry with location to my microsite directory
So that I can display the school location

## Notes

Maybe this is an opportunity to add a new directory entry type that is NOT called 'venue'. Place? Location? ...

### PR DESCRIPTION
**Pull request by stephen-cox**
~~Blocked by https://github.com/localgovdrupal/localgov_directories/pull/202~~

Fixes #108

### CODE REVIEW

**Comment by stephen-cox** [comment]
@msayoung This PR also fixes #158 and unblocks #148

**Review by finnlewis — APPROVED** [review]
Looks great, let's get this merged !

**Comment by stephen-cox** [comment]
Also fixes #159

**Comment by stephen-cox** [comment]
Merged! Thanks

**Pull request merged**
