### PR TITLE
Add promo page to the localgov_microsites_group

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by finnlewis** [comment]
Maria would like some other eyes on this, it's not working for her locally.

**Comment by msayoung** [comment]
When I run a site install this just hangs forever, I'm not sure what is causing this. Oddly the tests are passing here.  @finnlewis can you replicate?

**Comment by markconroy** [comment]
Hanging for me too.

But ... I think I am noticing something, or maybe not.

The branch for this seems to be cut from the `localgov_microsites_group` repo, but the code it targets is in the `localgov_microsites_directories` module. Am I right in that thinking? If so, we probably need to more this PR to the directories repo.

**Comment by msayoung** [comment]
I was following the pattern we have for bringing news an events in to microsites. A submodule within localgov_microsites_group https://github.com/localgovdrupal/localgov_microsites_group/tree/1.x/modules

**Comment by markconroy** [comment]
Sorry, that's my mistake. I was reading the folder names incorrectly. 

So, it looks like something in this is causing the install to hang indefinitely, but no error reported. I've no idea what that might be.

**Comment by stephen-cox** [comment]
This is likely to be hanging for the same reason venues fails; https://github.com/localgovdrupal/localgov_directories/issues/201

**Comment by stephen-cox** [comment]
This should work once #135 is merged.

**Comment by msayoung** [comment]
This works for me locally now! Whoop! Thanks @stephen-cox 
@finnlewis wanna give it a whirl and then we can merge?

**Review by stephen-cox — CHANGES_REQUESTED** [review]
Worked fine apart from the permissions weren't being installed. 

Looks like you should be using `group_node:localgov_directory_promo_page` in the permission name instead of `group_node:localgov_directories_promo_page`

**Comment by markconroy** [comment]
Looks good to me (once the permission issue @stephen-cox mentioned is sorted). Ready to merge then.

**Review by stephen-cox — APPROVED** [review]
Looks good now

**Pull request merged**
